
package transportadora.view;

import transportadora.view.cadastro.CadastroCaminhaoView;
import transportadora.view.cadastro.CadastroFornecedorView;
import transportadora.view.cadastro.CadastroMotoristaView;
import transportadora.view.cadastro.CadastroProdutoView;
import transportadora.view.consulta.ConsultaCaminhoes;
import transportadora.view.consulta.ConsultaFornecedores;
import transportadora.view.consulta.ConsultaMotoristas;
import transportadora.view.consulta.ConsultaPedidos;
import transportadora.view.consulta.ConsultaProdutos;
import transportadora.view.consulta.TableCaminhoes;
import transportadora.view.pedido.PedidoView;


/**
 *
 * @author USUARIO
 */
public class FrameView extends javax.swing.JFrame {

    /**
     * Creates new form FrameView
     */
    public FrameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jCadasFornecedor = new javax.swing.JMenuItem();
        jCadasCaminhao = new javax.swing.JMenuItem();
        jCadasMotorista = new javax.swing.JMenuItem();
        jCadasProduto = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jConMotorista = new javax.swing.JMenuItem();
        jConProdutos = new javax.swing.JMenuItem();
        jConCaminhoes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuPedido = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(300, 300));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportadora/view/logos de caminhoes.jpg"))); // NOI18N

        jMenuCadastro.setText("CADASTRO");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jCadasFornecedor.setText("FORNECEDOR");
        jCadasFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCadasFornecedorMouseClicked(evt);
            }
        });
        jCadasFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadasFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadasFornecedor);

        jCadasCaminhao.setText("CAMINHAO");
        jCadasCaminhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadasCaminhaoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadasCaminhao);

        jCadasMotorista.setText("MOTORISTA");
        jCadasMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadasMotoristaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadasMotorista);

        jCadasProduto.setText("PRODUTO");
        jCadasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadasProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadasProduto);

        jMenuBar.add(jMenuCadastro);

        jMenuConsulta.setText("CONSULTA");
        jMenuConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jConMotorista.setText("MOTORISTAS");
        jConMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConMotoristaActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jConMotorista);

        jConProdutos.setText("PRODUTOS");
        jConProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConProdutosActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jConProdutos);

        jConCaminhoes.setText("CAMINHOES");
        jConCaminhoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConCaminhoesActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jConCaminhoes);

        jMenuItem1.setText("FORNECEDORES");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItem1);

        jMenuBar.add(jMenuConsulta);

        jMenuPedido.setText("NOVO PEDIDO");
        jMenuPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuPedidoMousePressed(evt);
            }
        });
        jMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidoActionPerformed(evt);
            }
        });
        jMenuBar.add(jMenuPedido);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void jCadasFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCadasFornecedorMouseClicked
       
    }//GEN-LAST:event_jCadasFornecedorMouseClicked

    private void jCadasFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadasFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedorView forn = new CadastroFornecedorView();
        forn.setVisible(true);
    }//GEN-LAST:event_jCadasFornecedorActionPerformed

    private void jCadasCaminhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadasCaminhaoActionPerformed
        // TODO add your handling code here:
        CadastroCaminhaoView cam = new CadastroCaminhaoView();
        cam.setVisible(true);
    }//GEN-LAST:event_jCadasCaminhaoActionPerformed

    private void jCadasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadasProdutoActionPerformed
        // TODO add your handling code here:
        CadastroProdutoView prod = new CadastroProdutoView();
        prod.setVisible(true);
    }//GEN-LAST:event_jCadasProdutoActionPerformed

    private void jCadasMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadasMotoristaActionPerformed
        // TODO add your handling code here:
        CadastroMotoristaView moto = new CadastroMotoristaView();
        moto.setVisible(true);
    }//GEN-LAST:event_jCadasMotoristaActionPerformed

    private void jMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidoActionPerformed

    }//GEN-LAST:event_jMenuPedidoActionPerformed

    private void jMenuPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPedidoMousePressed
        // TODO add your handling code here:
        PedidoView pedidoView = new PedidoView();
        pedidoView.setVisible(true);
    }//GEN-LAST:event_jMenuPedidoMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ConsultaFornecedores consultafor = new ConsultaFornecedores();
        consultafor.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jConCaminhoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConCaminhoesActionPerformed
        // TODO add your handling code here:
        ConsultaCaminhoes caminhoes = new ConsultaCaminhoes();
        caminhoes.setVisible(true);
    }//GEN-LAST:event_jConCaminhoesActionPerformed

    private void jConProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConProdutosActionPerformed
        // TODO add your handling code here:
        ConsultaProdutos consultaProdutos = new ConsultaProdutos();
        consultaProdutos.setVisible(true);
    }//GEN-LAST:event_jConProdutosActionPerformed

    private void jConMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConMotoristaActionPerformed
        // TODO add your handling code here:
        ConsultaMotoristas motorista = new ConsultaMotoristas();
        motorista.setVisible(true);
    }//GEN-LAST:event_jConMotoristaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadasCaminhao;
    private javax.swing.JMenuItem jCadasFornecedor;
    private javax.swing.JMenuItem jCadasMotorista;
    private javax.swing.JMenuItem jCadasProduto;
    private javax.swing.JMenuItem jConCaminhoes;
    private javax.swing.JMenuItem jConMotorista;
    private javax.swing.JMenuItem jConProdutos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuPedido;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
